### ISSUE TITLE
make fails on non-Windows systems

### ISSUE THREAD

**Issue by samplx** [ogdenpm/thames-src#1]
The `make` step will fail during the final link due to the collision of the `thames` source directory name and the name of the output program. This is not an issue on Windows, since the output program is `thames.exe` rather than `thames`. I hit this on Mac OS X, but I am sure it is the same on Linux.

```
[ 18%] Linking C executable thames
/usr/local/Cellar/cmake/3.27.7/bin/cmake -E cmake_link_script CMakeFiles/thames.dir/link.txt --verbose=1
/Library/Developer/CommandLineTools/usr/bin/cc  -isysroot /Library/Developer/CommandLineTools/SDKs/MacOSX14.0.sdk -mmacosx-version-min=13.5 -Wl,-search_paths_first -Wl,-headerpad_max_install_names CMakeFiles/thames.dir/thames/_version.c.o CMakeFiles/thames.dir/thames/cmdline.c.o CMakeFiles/thames.dir/thames/errcheck.c.o CMakeFiles/thames.dir/thames/extensions.c.o CMakeFiles/thames.dir/thames/isis.c.o CMakeFiles/thames.dir/thames/isisfile.c.o CMakeFiles/thames.dir/thames/isisload.c.o CMakeFiles/thames.dir/thames/thames.c.o CMakeFiles/thames.dir/thames/utils.c.o CMakeFiles/thames.dir/thames/z80.c.o -o thames 
ld: open() failed, errno=21 for 'thames'
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make[2]: *** [thames] Error 1
make[1]: *** [CMakeFiles/thames.dir/all] Error 2
make: *** [all] Error 2
```

I didn't know if or how you would like to resolve this, so I didn't submit a PR.

**Comment by ogdenpm** [comment]
Jim
How did you invoke the build. With Ubuntu I did
cd to cloned file directory
mkdir builddir
cd builddir
cmake ..
cmake —build .


Regards
Mark Ogden
________________________________
From: Jim Burlingame ***@***.***>
Sent: Thursday, October 26, 2023 5:28:51 PM
To: ogdenpm/thames-src ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [ogdenpm/thames-src] make fails on non-Windows systems (Issue #1)


The make step will fail during the final link due to the collision of the thames source directory name and the name of the output program. This is not an issue on Windows, since the output program is thames.exe rather than thames. I hit this on Mac OS X, but I am sure it is the same on Linux.

[ 18%] Linking C executable thames
/usr/local/Cellar/cmake/3.27.7/bin/cmake -E cmake_link_script CMakeFiles/thames.dir/link.txt --verbose=1
/Library/Developer/CommandLineTools/usr/bin/cc  -isysroot /Library/Developer/CommandLineTools/SDKs/MacOSX14.0.sdk -mmacosx-version-min=13.5 -Wl,-search_paths_first -Wl,-headerpad_max_install_names CMakeFiles/thames.dir/thames/_version.c.o CMakeFiles/thames.dir/thames/cmdline.c.o CMakeFiles/thames.dir/thames/errcheck.c.o CMakeFiles/thames.dir/thames/extensions.c.o CMakeFiles/thames.dir/thames/isis.c.o CMakeFiles/thames.dir/thames/isisfile.c.o CMakeFiles/thames.dir/thames/isisload.c.o CMakeFiles/thames.dir/thames/thames.c.o CMakeFiles/thames.dir/thames/utils.c.o CMakeFiles/thames.dir/thames/z80.c.o -o thames
ld: open() failed, errno=21 for 'thames'
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make[2]: *** [thames] Error 1
make[1]: *** [CMakeFiles/thames.dir/all] Error 2
make: *** [all] Error 2


I didn't know if or how you would like to resolve this, so I didn't submit a PR.

**Comment by samplx** [comment]
I did
```bash
git clone https://github.com/ogdenpm/thames-src.git
cd thames-src
cmake .
make VERBOSE=1
```

I have a version with the `thames` directory renamed to `src`, although I would be fine with adding a note to the readme to build in a separate directory. I haven't used `cmake` very much so I just did what was simple.

Thanks for all your work on these tools, BTW.

**Comment by ogdenpm** [comment]
Jim

The standard cmake model would be to create a new build subdirectory off thames-src, change to it and invoke cmake from there.

This should avoid the conflict you are seeing.

Mark
